fix: transliterate snippets missing from tablet
cdklabs/jsii-docgen pull request #651
Opened 2022-04-07 23:22 UTC by MrArnoldPalmer

Catch failures of `transliterateAssembly` and rethrow as
`LanguageNotSupportedError`. This allows adding support for Go as some
package versions were released with Go support before jsii-rosetta
supported it and have a tablet file without Go snippets.

In the future live transliteration of these missing snippets may be
ideal but the only package I've found with this scenario is aws-cdk-lib,
which takes a really long time to live transliterate and is something we
may want to optimize further before enabling.

Furthermore only a handful of aws-cdk-lib versions actually have this
problem as the latest have correct Go snippets in the tablet, andd the
earliest dont' have tablet files at all and are therefore fully transliterated
by jsii-docgen.

2022-04-08 23:09 UTC, Chriscbr requested changes

2022-04-08 23:09 UTC, Chriscbr commented on API.md
> +# API Reference <a name="API Reference" id="api-reference"></a>
Remove this file

2022-04-08 23:10 UTC, Chriscbr approved these changes
Approving with `do-not-merge` label so you can merge it in after fixing the nit 👍

2022-04-11 09:53 UTC, merged

2022-04-11 10:01 UTC, RomainMuller commented on src/docgen/view/documentation.ts
> +            throw new LanguageNotSupportedError(`Laguage ${language} is not supported for package ${this.assemblyFqn}`);
Could have mentioned that this is a snippet translation issue....