support generating docs for mulitple languages
cdklabs/jsii-docgen pull request #903
Opened 2023-01-20 13:58 UTC by DanielMSchmidt

- feat!: support multiple languages as outputs
- feat: support splitting docs by submodules

2023-01-23 10:00 UTC, RomainMuller commented
I am pretty favorable to smaller, more focused files generally speaking. That naturally applies to documentation files, too.

---

One thing that can be interesting (optionally - I reckon that might be substantial additional complexity, possibly unwarranted), is to actually "collapse" the navigation tree when there some module-like item only contains a few module-like items... For example (this is all made up, obviously):

```
API.md -> (foo)foo.md -> (bar)bar.md -> (baz)baz.md -> [types within foo.bar.baz]
       -> (foo)foo.md -> (bar2)bar2.md -> [types within foo.bar2]
```

Could be rendered as:

```
API.md -> (foo.bar.baz)baz.md
       -> (foo.bar2)bar2.md
```

This improves the navigation path (fewer clicks, better discoverability) when there is a small enough number of submodules in a given module.

2023-01-23 11:41 UTC, DanielMSchmidt commented
I'm not sure I understand your comment 100%, let me try to rephrase it. You'd like to add an option so that instead of `Api.md -> Typescript -> <namespaceA>` and `Api.md -> Python -> <namespaceB>` you'd have a `Api.md` with a `Typescript` section, so that you can diectly click on `<namespaceA>` from within there?

2023-01-24 08:18 UTC, RomainMuller commented
I was "ignoring" the language specific section, because I think it's okay to single out languages (folks will want to be in the one language's context anyway).

The idea is if a namespace only contains a few items, instead of linking to a list page for that namespace, have links to all the `namespace.Item`s instead, so users don't have to hop through a dedicated page just for a short list of things.

2023-01-27 22:06 UTC, ryparker requested changes

2023-02-02 12:32 UTC, DanielMSchmidt commented on src/cli.ts
> +    .option('split-by-submodule', { type: 'boolean', required: false, desc: 'Generate a separate file for each submodule' })
Yeah, I think that makes sense :) The alternative would be to make two distinct entry points, one for the single-file generation and one that creates a directory, this way we could split up the args into two bucket and don't have this state where some make limited sense on one use-case or the other :)

2023-02-02 12:39 UTC, DanielMSchmidt commented on src/cli.ts
> +async function generateForLanguage(docs: Documentation, format: 'md' | 'json', options: GenerateOptions, output = 'API') {
Sure thing!

2023-02-16 15:20 UTC, RomainMuller commented on src/cli.ts
> +    fs.writeFileSync(`${output ?? 'API'}.${fileSuffix}`, await (await docs.toIndexMarkdown(submoduleSuffix, options)).render());
Feels a bit weird to use `Sync` FS APIs while you're using `await` there... Can you flip to using the promise versions (either from `fs/promises` or `import { promises as fs } from 'fs';`)?

2023-02-17 12:08 UTC, RomainMuller approved these changes

2023-02-17 12:22 UTC, merged

2023-02-20 10:29 UTC, mrgrain commented
@DanielMSchmidt @RomainMuller I think this accidentally introduced a breaking change.
This [line](https://github.com/cdklabs/jsii-docgen/pull/903/files#diff-fa8d4e24d8399e8350f1c8bad05df53e8032ea995835bf911507015e2db61cddR86) changes the behaviour of `--output` from requiring an extension to not needing one, causing something like `jsii-docgen -o API.md` to now create a file named `API.md.md`.

At least this needs to be a breaking release. But saying that, it's a very annoying change for `projen` since it breaks the CLI contract for previous versions. 

See: https://github.com/projen/projen/issues/2458

2023-02-20 10:37 UTC, DanielMSchmidt commented
Oh no, I'll provide a fix as soon as possible